"""
JAX-based Occupancy Grid Map for TPU-accelerated training.

Faithful port of the NumPy OccupancyGridMap for use with PureJaxRL-style
vectorized training on TPU.

Key design decisions:
- All state is immutable (functional updates via NamedTuple._replace).
- n (number of modules) is always a compile-time static constant; every
  function that depends on n takes it via static_argnums or receives it
  through a statically-shaped array.
- The occupancy grid is stored ONLY as an (n,3) position array.  A dense
  3D grid is reconstructed on-the-fly when pivot validation needs it.
  This avoids storing/updating a large sparse grid in traced code.
- Pivot validation uses pre-computed (48, 3, 3, 3) pattern tables that
  are exact ports of potential_pivots / ranges from the NumPy version.
- pivot_zone_grid_map is NOT ported (it is a minor optimisation in the
  original that slightly restricts legal moves after a pivot; omitting it
  makes the action space a superset of the NumPy version -- all moves the
  NumPy code allows are still allowed, plus a few extra that the zone
  mechanic would block).  This is acceptable for RL training.
- Articulation-point detection uses BFS-based connectivity checking
  (remove node, check reachability) which is JIT-compatible via lax.scan.
- Hungarian assignment for unlabeled matching uses a JAX-compatible
  implementation based on sorted-row signatures, which is exact for the
  pairwise-norm distance matrices arising in this problem.
"""

import jax
import jax.numpy as jnp
from jax import lax
from functools import partial
from typing import NamedTuple, Tuple
import chex
import numpy as np


# ============================================
# Static lookup tables (numpy, converted to
# JAX arrays at first use via _get_* helpers)
# ============================================

# --- Action deltas (48 pivots, 0-indexed) ---
# Extracted directly from take_action() in occupancy_grid_map.py.
# Row i  =>  action (i+1) in the NumPy code.
# Action 48 (index 48) is the no-op; handled separately.
_ACTION_DELTAS_NP = np.array(
    [
        # Actions  1- 4  (xy-plane, +x side)
        [1, 0, 0],
        [1, -1, 0],
        [1, 0, 0],
        [1, 1, 0],
        # Actions  5- 8  (xy-plane, +y / -y)
        [0, 1, 0],
        [1, 1, 0],
        [0, -1, 0],
        [1, -1, 0],
        # Actions  9-12  (xy-plane, -x side)
        [-1, 0, 0],
        [-1, -1, 0],
        [-1, 0, 0],
        [-1, 1, 0],
        # Actions 13-16  (xy-plane, +y / -y other)
        [0, 1, 0],
        [-1, 1, 0],
        [0, -1, 0],
        [-1, -1, 0],
        # Actions 17-20  (xz-plane, +x side)
        [1, 0, 0],
        [1, 0, -1],
        [1, 0, 0],
        [1, 0, 1],
        # Actions 21-24  (xz-plane, +z / -z)
        [0, 0, 1],
        [1, 0, 1],
        [0, 0, -1],
        [1, 0, -1],
        # Actions 25-28  (xz-plane, -x side)
        [-1, 0, 0],
        [-1, 0, -1],
        [-1, 0, 0],
        [-1, 0, 1],
        # Actions 29-32  (xz-plane, +z / -z other)
        [0, 0, 1],
        [-1, 0, 1],
        [0, 0, -1],
        [-1, 0, -1],
        # Actions 33-36  (yz-plane, +y side)
        [0, 1, 0],
        [0, 1, -1],
        [0, 1, 0],
        [0, 1, 1],
        # Actions 37-40  (yz-plane, +z / -z)
        [0, 0, 1],
        [0, 1, 1],
        [0, 0, -1],
        [0, 1, -1],
        # Actions 41-44  (yz-plane, -y side)
        [0, -1, 0],
        [0, -1, -1],
        [0, -1, 0],
        [0, -1, 1],
        # Actions 45-48  (yz-plane, +z / -z other)
        [0, 0, 1],
        [0, -1, 1],
        [0, 0, -1],
        [0, -1, -1],
    ],
    dtype=np.int32,
)  # shape (48, 3)

NUM_ACTIONS = 49  # 48 pivots + 1 no-op (index 48)

# --- Pivot validation tables ---
# Each of the 48 pivot actions requires a specific occupancy pattern in a
# 3D neighbourhood around the acting module.  The neighbourhood is defined
# by PIVOT_OFFSETS (the corner closest to the module) and extends at most
# 3 cells in each axis.  We pad everything to (48, 3, 3, 3) so shapes are
# static.
#
# PIVOT_PATTERN[a, x, y, z] == 1  means that grid cell
#     (module_pos + PIVOT_OFFSETS[a] + (x, y, z))
#   must be OCCUPIED for action a to be valid.
#
# PIVOT_CHECK[a, x, y, z] == 1   means that cell is part of the validation
#   region (cells outside are ignored).
#
# The validation rule is:
#   for every (x,y,z) where PIVOT_CHECK[a]==1:
#     occupied[cell] == bool(PIVOT_PATTERN[a, x, y, z])
#   i.e. the actual occupancy in the check region must EXACTLY equal the
#   pattern (both occupied AND empty cells must match).
#
# Generated by expanding potential_pivots[] / ranges[] from the NumPy code.

_PIVOT_PATTERN_NP = np.array(
    [
        [
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [1, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 1, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [1, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 1, 1], [0, 0, 1], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [1, 0, 0], [1, 1, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 1, 0], [1, 1, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 1], [0, 0, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 1, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [1, 1, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 1], [0, 1, 1], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 1, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [1, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 1, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 1], [0, 0, 1], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
    ],
    dtype=np.uint8,
)  # (48, 3, 3, 3)

_PIVOT_CHECK_NP = np.array(
    [
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [1, 1, 0], [1, 1, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [1, 1, 0], [1, 1, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [1, 1, 0], [1, 1, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [1, 1, 0], [1, 1, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
    ],
    dtype=np.uint8,
)  # (48, 3, 3, 3)

# Corner offset (relative to module position) for each action's 3x3x3 check window.
_PIVOT_OFFSETS_NP = np.array(
    [
        [0, -1, 0],
        [0, -1, 0],
        [0, -1, 0],
        [0, -1, 0],
        [-1, 0, 0],
        [-1, 0, 0],
        [-1, -1, 0],
        [-1, -2, 0],
        [-1, -1, 0],
        [-2, -1, 0],
        [-1, -1, 0],
        [-2, -1, 0],
        [-1, 0, 0],
        [-1, 0, 0],
        [-1, -1, 0],
        [-1, -2, 0],
        [0, 0, -1],
        [0, 0, -1],
        [0, 0, -1],
        [0, 0, -1],
        [-1, 0, 0],
        [-1, 0, 0],
        [-1, 0, -1],
        [-1, 0, -2],
        [-1, 0, -1],
        [-2, 0, -1],
        [-1, 0, -1],
        [-2, 0, -1],
        [-1, 0, 0],
        [-1, 0, 0],
        [-1, 0, -1],
        [-1, 0, -2],
        [0, 0, -1],
        [0, 0, -1],
        [0, 0, -1],
        [0, 0, -1],
        [0, -1, 0],
        [0, -1, 0],
        [0, -1, -1],
        [0, -1, -2],
        [0, -1, -1],
        [0, -2, -1],
        [0, -1, -1],
        [0, -2, -1],
        [0, -1, 0],
        [0, -1, 0],
        [0, -1, -1],
        [0, -1, -2],
    ],
    dtype=np.int32,
)  # (48, 3)


# ---- Eager JAX constant arrays (converted at import time, never inside JIT) ----
# These are static lookup tables; converting them once at module load avoids
# tracer-leak errors that occur if conversion happens inside a jit-traced call.
ACTION_DELTAS = jnp.array(_ACTION_DELTAS_NP)  # (48, 3)  int32
PIVOT_PATTERN = jnp.array(_PIVOT_PATTERN_NP)  # (48, 3, 3, 3) uint8
PIVOT_CHECK = jnp.array(_PIVOT_CHECK_NP)  # (48, 3, 3, 3) uint8
PIVOT_OFFSETS = jnp.array(_PIVOT_OFFSETS_NP)  # (48, 3)  int32


def get_action_deltas():
    return ACTION_DELTAS


def get_pivot_pattern():
    return PIVOT_PATTERN


def get_pivot_check():
    return PIVOT_CHECK


def get_pivot_offsets():
    return PIVOT_OFFSETS


# ============================================
# Data Structures
# ============================================


class OGMState(NamedTuple):
    """Immutable state for one environment instance."""

    module_positions: chex.Array  # (n, 3) int32 - current positions
    final_positions: chex.Array  # (n, 3) int32 - target positions
    step_count: int  # current step (scalar int32)
    max_steps: int  # episode length limit (scalar int32)
    # agent_idx tracks whose turn it is (round-robin)
    agent_idx: int  # scalar int32
    # Milestone tracking for partial progress rewards (matches PyTorch baseline)
    initial_norm_diff: float  # frobenius norm of initial config distance
    milestone_50: bool  # whether 50% progress bonus was awarded
    milestone_75: bool  # whether 75% progress bonus was awarded
    milestone_90: bool  # whether 90% progress bonus was awarded
    # Cached sorted signatures for observation/reward consistency
    # These are updated every step and represent the optimal row-alignment
    # between current and final configs (permutation-invariant).
    final_sorted_sigs: (
        chex.Array
    )  # (n, n-1) float32 - sorted distance signatures for final config
    curr_assignment: (
        chex.Array
    )  # (n,) int32 - current best row-mapping from curr->final signatures
    # Soft matching reward state
    phi_max: float  # running best soft matching score (ratchet)
    final_sqdist: chex.Array  # (n, n) float32 - cached final squared distances


class OGMConfig(NamedTuple):
    """Static (non-traced) configuration."""

    n: int
    max_steps: int
    grid_size: int  # half-width for the dense grid used in validation
    use_unlabeled: bool
    local_k: int
    # Reward configuration
    enable_soft_matching: bool = False
    soft_matching_scale: float = 100.0
    soft_matching_decay_beta: float = 0.999
    enable_potential: bool = True
    potential_scale: float = 1.0
    success_bonus: float = 100.0
    step_cost: float = -0.005
    use_exponential_step_cost: bool = False
    step_cost_initial: float = -0.01
    step_cost_min: float = -0.001


# ============================================
# Utility: build a dense occupancy grid from
# (n,3) positions.  grid_size must be large
# enough that all positions fit inside
# [0, 2*grid_size).
# ============================================


@partial(jax.jit, static_argnums=(1,))
def _build_grid(positions: chex.Array, grid_size: int) -> chex.Array:
    """Return a (2*gs, 2*gs, 2*gs) bool grid marking occupied cells."""
    side = 2 * grid_size
    grid = jnp.zeros((side, side, side), dtype=jnp.bool_)

    # scatter True at each position
    def _set(g, pos):
        return g.at[pos[0], pos[1], pos[2]].set(True), None

    grid, _ = lax.scan(_set, grid, positions)
    return grid


# ============================================
# Core: pairwise norms
# ============================================


@jax.jit
def compute_pairwise_norms(positions: chex.Array) -> chex.Array:
    """(n,3) -> (n,n) L2 distances."""
    diff = positions[:, None, :] - positions[None, :, :]  # (n, n, 3)
    return jnp.sqrt(jnp.sum(diff * diff, axis=-1))


# ============================================
# Observation reductions (four-band + local-k)
# ============================================


@jax.jit
def calc_four_band_reduction(pairwise_norms: chex.Array) -> chex.Array:
    """(n,n) -> (n,4).  Offsets [-2,-1,+1,+2] with circular wrapping."""
    n = pairwise_norms.shape[0]
    idx = jnp.arange(n)
    bands = []
    for offset in [-2, -1, 1, 2]:
        j = (idx + offset) % n
        bands.append(pairwise_norms[idx, j])  # (n,)
    return jnp.stack(bands, axis=1)  # (n, 4)


@partial(jax.jit, static_argnums=(2,))
def calc_local_neighborhood(reduced: chex.Array, agent_idx: int, k: int) -> chex.Array:
    """(n, 4) -> (k, 4) window centred on agent_idx."""
    n = reduced.shape[0]
    half_k = k // 2
    offsets = jnp.arange(k) - half_k  # (-half_k .. k-half_k-1)
    indices = (agent_idx + offsets) % n
    return reduced[indices]  # (k, 4)


# ============================================
# Connectivity & articulation-point detection
# ============================================


@partial(jax.jit, static_argnums=(1,))
def _build_adjacency(positions: chex.Array, n: int) -> chex.Array:
    """Return (n,n) bool adjacency matrix (Manhattan dist == 1)."""
    diff = positions[:, None, :] - positions[None, :, :]  # (n,n,3)
    manhattan = jnp.sum(jnp.abs(diff), axis=-1)  # (n,n)
    return manhattan == 1  # (n,n) bool


@partial(jax.jit, static_argnums=(2,))
def _bfs_reachable(adj: chex.Array, start: int, n: int) -> chex.Array:
    """BFS from `start` using matrix-power expansion.  Returns (n,) bool visited."""
    visited = jnp.zeros(n, dtype=jnp.bool_).at[start].set(True)

    def _step(visited, _):
        # any neighbour of a visited node becomes visited
        new_visited = jnp.any(adj & visited[None, :], axis=1) | visited
        return new_visited, None

    visited, _ = lax.scan(_step, visited, None, length=n)
    return visited


@partial(jax.jit, static_argnums=(1,))
def is_articulation_point(positions: chex.Array, n: int) -> chex.Array:
    """Return (n,) bool array: True where module is an articulation point.

    A module is an AP if removing it disconnects the remaining graph.
    We check this by: for each candidate i, mask row/col i out of the
    adjacency matrix, pick the first remaining node as BFS root, and
    check if all other remaining nodes are reached.
    """
    adj = _build_adjacency(positions, n)  # (n,n)

    def _check_one(i):
        # mask out node i
        mask = jnp.arange(n) != i  # (n,) bool
        adj_masked = adj & mask[:, None] & mask[None, :]  # zero row & col i

        # BFS root: first node that is not i
        # Use (i+1) % n so it wraps around
        root = (i + 1) % n

        visited = _bfs_reachable(adj_masked, root, n)  # (n,)

        # All nodes except i must be visited
        expected = mask  # (n,) True everywhere except i
        return ~jnp.all(visited == expected)  # True => disconnected => AP

    return jax.vmap(_check_one)(jnp.arange(n))  # (n,)


# ============================================
# Pivot validation (action mask)
# ============================================


@partial(jax.jit, static_argnums=(1, 2))
def get_action_mask(positions: chex.Array, n: int, grid_size: int) -> chex.Array:
    """Return (49,) bool mask of valid actions for agent at positions[agent_idx].

    Checks:
      1. Module must NOT be an articulation point.
      2. For each of the 48 pivot actions, the 3x3x3 neighbourhood occupancy
         must exactly match the pre-computed PIVOT_PATTERN (ports the
         potential_pivots check from the NumPy version).
      3. Action 48 (no-op) is always valid.

    agent_idx is encoded implicitly: this function returns the mask for
    agent 0.  The caller rotates the position array so that the acting
    agent is always index 0 -- see _rotate_for_agent().
    """
    # --- build dense grid ---
    # Shift positions so minimum is at least 2 (buffer for negative offsets
    # in PIVOT_OFFSETS which go down to -2).
    # We use a fixed shift of grid_size so that positions land in the middle.
    shifted = positions + grid_size  # (n, 3) int32
    side = 2 * grid_size
    grid = _build_grid(shifted, grid_size)  # (side,side,side) bool

    # --- articulation point for agent 0 ---
    ap_mask = is_articulation_point(positions, n)  # (n,)
    agent_is_ap = ap_mask[0]  # scalar bool

    # --- pattern check for all 48 actions ---
    agent_pos = shifted[0]  # (3,) shifted position of agent 0

    pattern = get_pivot_pattern()  # (48, 3, 3, 3) uint8
    check = get_pivot_check()  # (48, 3, 3, 3) uint8
    offsets = get_pivot_offsets()  # (48, 3) int32

    def _check_action(a):
        """Check one pivot action a in [0..47]."""
        # Corner of the 3x3x3 window in the shifted grid
        corner = agent_pos + offsets[a]  # (3,)

        # Extract the 3x3x3 sub-grid.  Use dynamic_slice (JIT-safe).
        sub = lax.dynamic_slice(grid, corner, (3, 3, 3))  # (3,3,3) bool

        # Compare: where check==1, sub must equal pattern
        pat = pattern[a].astype(jnp.bool_)  # (3,3,3)
        chk = check[a].astype(jnp.bool_)  # (3,3,3)

        # Mismatch at any checked cell => invalid
        mismatch = chk & (sub != pat)
        return ~jnp.any(mismatch)  # True => valid

    pivot_valid = jax.vmap(_check_action)(jnp.arange(48))  # (48,) bool

    # If agent is AP, no pivot is valid
    pivot_valid = jnp.where(agent_is_ap, jnp.zeros(48, dtype=jnp.bool_), pivot_valid)

    # Append no-op (always valid)
    return jnp.concatenate([pivot_valid, jnp.array([True])])  # (49,)


# ============================================
# Permutation-invariant distance computation
# (Matches PyTorch's Hungarian-based approach)
# ============================================


@jax.jit
def compute_sorted_signatures(norms: chex.Array) -> chex.Array:
    """Compute per-module sorted distance signatures.

    For each module i, its "signature" is the sorted vector of distances
    to all other modules.  This is permutation-invariant: renaming the
    modules doesn't change the set of signatures.

    Args:
        norms: (n, n) pairwise L2 distances

    Returns:
        (n, n) float32 -- row i is the sorted distances from module i
        to all modules (including self=0 at position 0).
    """
    return jnp.sort(norms, axis=1)  # (n, n)


@jax.jit
def compute_signature_cost_matrix(
    curr_sigs: chex.Array, final_sigs: chex.Array
) -> chex.Array:
    """Compute (n, n) cost matrix for matching current signatures to final signatures.

    cost[i, j] = ||curr_sigs[i] - final_sigs[j]||^2

    This is the JAX equivalent of PyTorch's calc_cost_assignment_matrix.
    """
    # curr_sigs: (n, n), final_sigs: (n, n)
    # Broadcast: (n, 1, n) - (1, n, n) -> (n, n, n) -> sum over last -> (n, n)
    diff = curr_sigs[:, None, :] - final_sigs[None, :, :]  # (n, n, n)
    return jnp.sum(diff * diff, axis=-1)  # (n, n)


@partial(jax.jit, static_argnums=(1,))
def greedy_assignment(cost_matrix: chex.Array, n: int) -> chex.Array:
    """Greedy approximation to the assignment problem (JIT-compatible).

    Uses iterative argmin-based assignment: for each row in order,
    pick the cheapest unassigned column.  Not optimal but O(n^2) and
    fully traceable.  For the distance matrices in this problem
    (where the structure is highly regular), this produces near-optimal
    assignments.

    Args:
        cost_matrix: (n, n) float32
        n: number of items (static)

    Returns:
        (n,) int32 -- assignment[i] = column assigned to row i
    """
    INF = jnp.float32(1e12)

    def _assign_one(carry, row_idx):
        cost, taken = carry
        # Mask out already-taken columns
        masked_cost = jnp.where(taken, INF, cost[row_idx])
        col = jnp.argmin(masked_cost)
        taken = taken.at[col].set(True)
        return (cost, taken), col

    taken = jnp.zeros(n, dtype=jnp.bool_)
    (_, _), assignments = lax.scan(_assign_one, (cost_matrix, taken), jnp.arange(n))
    return assignments.astype(jnp.int32)  # (n,)


@jax.jit
def compute_reassigned_diff(
    curr_norms: chex.Array,
    final_norms: chex.Array,
    assignment: chex.Array,
) -> chex.Array:
    """Compute (curr_pairwise - reassigned_final_pairwise) using the given assignment.

    This matches PyTorch's calc_rearranged_mat + subtraction.
    The result is an (n, n) matrix where 0 = goal achieved for that pair.

    Args:
        curr_norms:  (n, n) current pairwise distances
        final_norms: (n, n) final pairwise distances
        assignment:  (n,) int32 mapping curr_row -> final_row

    Returns:
        (n, n) float32 difference matrix (0 at goal)
    """
    # Rearrange final_norms according to assignment:
    # reassigned[i, j] = final_norms[assignment[i], assignment[j]]
    reassigned_final = final_norms[assignment][:, assignment]
    return curr_norms - reassigned_final


@partial(jax.jit, static_argnums=(1,))
def compute_assignment(
    curr_positions: chex.Array, final_positions: chex.Array, n: int
) -> chex.Array:
    """Compute greedy assignment from current to final configuration.

    Returns:
        (n,) int32 assignment
    """
    curr_norms = compute_pairwise_norms(curr_positions)
    final_norms = compute_pairwise_norms(final_positions)
    curr_sigs = compute_sorted_signatures(curr_norms)
    final_sigs = compute_sorted_signatures(final_norms)
    cost = compute_signature_cost_matrix(curr_sigs, final_sigs)
    return greedy_assignment(cost, n)


# ============================================
# Success check (unlabeled: consistent with
# the reassigned pairwise norm approach)
# ============================================


@jax.jit
def check_success(
    module_positions: chex.Array, final_positions: chex.Array, tol: float = 1e-6
) -> bool:
    """True if the current shape matches the target (up to permutation).

    Uses sorted-row double-sort signature comparison which is exact for
    the distance matrices arising from 3D grid positions.
    """
    curr = compute_pairwise_norms(module_positions)
    final = compute_pairwise_norms(final_positions)
    # Sort each row -> canonical per-module signature
    curr_sorted = jnp.sort(curr, axis=1)
    final_sorted = jnp.sort(final, axis=1)
    # Sort the rows themselves so the overall signature is permutation-invariant
    curr_sig = jnp.sort(curr_sorted, axis=0)
    final_sig = jnp.sort(final_sorted, axis=0)
    return jnp.allclose(curr_sig, final_sig, atol=tol)


# ============================================
# Reward / potential
# (Uses Frobenius norm of reassigned difference
#  matrix, matching PyTorch's approach)
# ============================================


@jax.jit
def compute_potential_from_diff(diff_matrix: chex.Array) -> float:
    """Potential = Frobenius norm of (curr - reassigned_final) pairwise norms.

    Matches PyTorch: np.linalg.norm(self.ogm.curr_pairwise_norms, 'fro')
    where curr_pairwise_norms = current - reassigned_final.
    """
    return jnp.linalg.norm(diff_matrix, "fro")


# ============================================
# Soft matching reward (ported from ogm_env.py)
# ============================================


@jax.jit
def compute_soft_matching_score(
    curr_sqdist: chex.Array, final_sqdist: chex.Array
) -> float:
    """Compute normalised soft pairwise matching score Φ(M).

    Φ(M) = (2 / (n(n-1))) Σ_{u<v} 1 / (1 + (D_uv - D_uv_goal)²)

    Returns value in (0, 1], where 1 = perfect match.
    Exact port of OGMEnv.compute_soft_matching_score().
    """
    n = curr_sqdist.shape[0]
    diff = curr_sqdist - final_sqdist
    scores = 1.0 / (1.0 + diff * diff)
    # Only count upper triangle (pairs u < v)
    mask = jnp.triu(jnp.ones((n, n), dtype=jnp.bool_), k=1)
    total = jnp.sum(scores * mask)
    return 2.0 * total / jnp.maximum(jnp.float32(n * (n - 1)), 1.0)


@jax.jit
def compute_unlabeled_soft_matching_score(
    curr_sqdist: chex.Array,
    final_sqdist: chex.Array,
    assignment: chex.Array,
) -> float:
    """Compute label-agnostic soft matching score using sorted-row signatures.

    Uses the pre-computed assignment to align current and final signatures,
    then computes per-element soft matching.  Exact port of
    OGMEnv.compute_unlabeled_soft_matching_score() but JIT-compatible
    (no scipy).

    Returns value in (0, 1], where 1 = perfect match.
    """
    n = curr_sqdist.shape[0]
    # Sort each row (signatures); keep self-distance (0) which will be at index 0
    curr_sigs = jnp.sort(curr_sqdist, axis=1)[:, 1:]   # (n, n-1)
    final_sigs = jnp.sort(final_sqdist, axis=1)[:, 1:]  # (n, n-1)
    # Align final signatures to current using assignment
    aligned_final = final_sigs[assignment]  # (n, n-1)
    diff_sq = (curr_sigs - aligned_final) ** 2
    scores = 1.0 / (1.0 + diff_sq)
    return jnp.sum(scores) / jnp.maximum(jnp.float32(n * (n - 1)), 1.0)


@jax.jit
def compute_pairwise_sqdist(positions: chex.Array) -> chex.Array:
    """Compute (n, n) squared L2 distance matrix."""
    diff = positions[:, None, :] - positions[None, :, :]  # (n, n, 3)
    return jnp.sum(diff * diff, axis=-1).astype(jnp.float32)  # (n, n)


@partial(jax.jit, static_argnums=(12,))
def compute_reward(
    prev_positions: chex.Array,
    curr_positions: chex.Array,
    final_positions: chex.Array,
    initial_norm_diff: float,
    milestone_50: bool,
    milestone_75: bool,
    milestone_90: bool,
    prev_assignment: chex.Array,
    final_sorted_sigs: chex.Array,
    phi_max: float,
    final_sqdist: chex.Array,
    step_count: int,
    config: OGMConfig,
) -> tuple:
    """Shaped reward: step_cost + potential shaping + soft matching + success + milestones.

    Matches PyTorch reward computation with all reward modes:
    - Potential = Frobenius norm of (curr_pairwise - reassigned_final_pairwise)
    - Shaping = (prev_potential - curr_potential) / n
    - Soft matching = w(t) * max(0, Φ(t+1) - Φ_max(t)) (ratchet-style)
    - Milestone bonuses at 50%, 75%, 90% progress
    - Exponential or flat step cost

    The assignment is updated greedily every step to track the best mapping.

    Returns:
        (reward, new_m50, new_m75, new_m90, new_assignment, new_phi_max)
    """
    n = prev_positions.shape[0]

    # Compute norms
    prev_norms = compute_pairwise_norms(prev_positions)
    curr_norms = compute_pairwise_norms(curr_positions)
    final_norms = compute_pairwise_norms(final_positions)

    # Update assignment using current configuration
    curr_sigs = compute_sorted_signatures(curr_norms)
    cost = compute_signature_cost_matrix(curr_sigs, final_sorted_sigs)
    new_assignment = greedy_assignment(cost, n)

    # --- 1. Potential-based shaping reward ---
    prev_diff = compute_reassigned_diff(prev_norms, final_norms, prev_assignment)
    curr_diff = compute_reassigned_diff(curr_norms, final_norms, new_assignment)
    prev_phi = compute_potential_from_diff(prev_diff)
    curr_phi = compute_potential_from_diff(curr_diff)

    # Normalize by n to keep reward scale consistent (critical for curriculum)
    potential_reward = jnp.where(
        config.enable_potential,
        config.potential_scale * (prev_phi - curr_phi) / jnp.float32(n),
        0.0,
    )

    # --- 2. Soft matching reward (ratchet-style, ported from ogm_env.py) ---
    curr_sqdist = compute_pairwise_sqdist(curr_positions)
    # Compute phi using labeled or unlabeled mode
    phi_labeled = compute_soft_matching_score(curr_sqdist, final_sqdist)
    phi_unlabeled = compute_unlabeled_soft_matching_score(
        curr_sqdist, final_sqdist, new_assignment
    )
    phi_current = jnp.where(config.use_unlabeled, phi_unlabeled, phi_labeled)

    # Time decay weight: w(t) = beta^t
    w_t = config.soft_matching_decay_beta ** step_count
    # Reward = w(t) * max(0, Φ(t+1) - Φ_max(t)) * scale
    improvement = phi_current - phi_max
    soft_reward = jnp.where(
        config.enable_soft_matching & (improvement > 0),
        w_t * improvement * config.soft_matching_scale,
        0.0,
    )
    # Update running best
    new_phi_max = jnp.where(
        config.enable_soft_matching & (improvement > 0),
        phi_current,
        phi_max,
    )

    # --- 3. Success bonus ---
    done = check_success(curr_positions, final_positions)
    bonus = jnp.where(done, config.success_bonus, 0.0)

    # --- 4. Milestone bonuses for partial progress ---
    milestone_bonus = jnp.float32(0.0)
    new_m50, new_m75, new_m90 = milestone_50, milestone_75, milestone_90

    progress = jnp.where(
        initial_norm_diff > 0,
        1.0 - (curr_phi / initial_norm_diff),
        0.0,
    )

    award_90 = ~done & (progress >= 0.9) & ~milestone_90
    milestone_bonus = jnp.where(award_90, config.success_bonus * 0.3, milestone_bonus)
    new_m90 = new_m90 | award_90

    award_75 = ~done & (progress >= 0.75) & ~milestone_75 & ~award_90
    milestone_bonus = jnp.where(award_75, config.success_bonus * 0.2, milestone_bonus)
    new_m75 = new_m75 | award_75

    award_50 = ~done & (progress >= 0.5) & ~milestone_50 & ~award_75 & ~award_90
    milestone_bonus = jnp.where(award_50, config.success_bonus * 0.1, milestone_bonus)
    new_m50 = new_m50 | award_50

    # --- 5. Step cost (flat or exponential decay) ---
    # Exponential: max(initial * exp(-rate * t), min)
    # decay_rate = -ln(min / initial) / max_steps
    decay_rate = jnp.where(
        config.use_exponential_step_cost & (config.step_cost_initial != 0.0),
        -jnp.log(jnp.abs(config.step_cost_min / config.step_cost_initial))
        / jnp.maximum(jnp.float32(config.max_steps), 1.0),
        0.0,
    )
    exp_cost = jnp.maximum(
        config.step_cost_initial * jnp.exp(-decay_rate * jnp.float32(step_count)),
        config.step_cost_min,
    )
    current_step_cost = jnp.where(
        config.use_exponential_step_cost, exp_cost, config.step_cost
    )

    # --- Total reward ---
    total_reward = potential_reward + soft_reward + bonus + milestone_bonus + current_step_cost
    return total_reward, new_m50, new_m75, new_m90, new_assignment, new_phi_max


# ============================================
# Random connected configuration generator
# ============================================


@partial(jax.jit, static_argnums=(1,))
def make_connected_configuration(key: chex.PRNGKey, n: int) -> chex.Array:
    """Grow a random connected structure of n cubes via BFS-style growth.

    Returns (n, 3) int32 positions centred near the origin.
    """
    # 6 face-adjacent directions
    DIRS = jnp.array(
        [[1, 0, 0], [-1, 0, 0], [0, 1, 0], [0, -1, 0], [0, 0, 1], [0, 0, -1]],
        dtype=jnp.int32,
    )

    # Start at origin
    positions = jnp.zeros((n, 3), dtype=jnp.int32)  # pre-allocated
    filled = jnp.zeros(n, dtype=jnp.bool_).at[0].set(True)

    def _add_one(carry, key_i):
        positions, filled, count = carry

        # For every filled position, compute 6 candidate neighbours
        # Shape: (n, 6, 3)
        candidates = positions[:, None, :] + DIRS[None, :, :]
        candidates_flat = candidates.reshape(-1, 3)  # (n*6, 3)

        # Mask: candidate comes from a filled slot
        from_filled = jnp.repeat(filled, 6)  # (n*6,)

        # Mask: candidate is not already occupied
        def _is_free(pos):
            matches = jnp.all(positions == pos[None, :], axis=1) & filled
            return ~jnp.any(matches)

        free_mask = jax.vmap(_is_free)(candidates_flat)  # (n*6,)

        valid = from_filled & free_mask  # (n*6,)

        # Sample uniformly among valid candidates
        logits = jnp.where(valid, 0.0, -1e9)
        idx = jax.random.categorical(key_i, logits)

        new_pos = candidates_flat[idx]  # (3,)
        positions = positions.at[count].set(new_pos)
        filled = filled.at[count].set(True)

        return (positions, filled, count + 1), None

    keys = jax.random.split(key, n - 1)
    (positions, _, _), _ = lax.scan(_add_one, (positions, filled, 1), keys)

    return positions


# ============================================
# Environment reset
# ============================================


@partial(jax.jit, static_argnums=(1,))
def reset(key: chex.PRNGKey, config: OGMConfig) -> OGMState:
    """Create a fresh episode with random initial & target configurations."""
    key1, key2 = jax.random.split(key)
    init_pos = make_connected_configuration(key1, config.n)
    final_pos = make_connected_configuration(key2, config.n)

    # Compute initial assignment and norm diff (matching PyTorch reset)
    init_norms = compute_pairwise_norms(init_pos)
    final_norms = compute_pairwise_norms(final_pos)

    # Pre-compute sorted signatures for the final config (static for episode)
    final_sorted_sigs = compute_sorted_signatures(final_norms)  # (n, n)

    # Initial assignment: curr -> final via greedy signature matching
    init_sigs = compute_sorted_signatures(init_norms)
    cost = compute_signature_cost_matrix(init_sigs, final_sorted_sigs)
    init_assignment = greedy_assignment(cost, config.n)

    # Initial potential = Frobenius norm of reassigned diff (matches PyTorch)
    init_diff = compute_reassigned_diff(init_norms, final_norms, init_assignment)
    initial_norm_diff = jnp.linalg.norm(init_diff, "fro")

    # Pre-compute final squared distances for soft matching reward
    final_sqdist = compute_pairwise_sqdist(final_pos)  # (n, n)

    # Initial soft matching score (phi_max starts at initial value)
    init_sqdist = compute_pairwise_sqdist(init_pos)
    phi_labeled = compute_soft_matching_score(init_sqdist, final_sqdist)
    phi_unlabeled = compute_unlabeled_soft_matching_score(
        init_sqdist, final_sqdist, init_assignment
    )
    init_phi = jnp.where(config.use_unlabeled, phi_unlabeled, phi_labeled)
    # Only track phi_max when soft matching is enabled
    init_phi_max = jnp.where(config.enable_soft_matching, init_phi, 0.0)

    return OGMState(
        module_positions=init_pos,
        final_positions=final_pos,
        step_count=jnp.int32(0),
        max_steps=jnp.int32(config.max_steps),
        agent_idx=jnp.int32(0),
        initial_norm_diff=initial_norm_diff,
        milestone_50=False,
        milestone_75=False,
        milestone_90=False,
        final_sorted_sigs=final_sorted_sigs,
        curr_assignment=init_assignment,
        phi_max=init_phi_max,
        final_sqdist=final_sqdist,
    )


# ============================================
# Observation
# ============================================


@partial(jax.jit, static_argnums=(3,))
def get_observation(
    module_positions: chex.Array,
    final_positions: chex.Array,
    agent_idx: int,
    local_k: int,
    assignment: chex.Array,
) -> chex.Array:
    """Flat observation vector of size (local_k * 4 + 4).

    Matches PyTorch observation computation:
      - Computes (curr_pairwise - reassigned_final_pairwise) using the
        current assignment (permutation-invariant for unlabeled mode).
      - Applies four-band reduction and local neighborhood windowing.
      - Normalises by max grid distance.
      - Appends 4-dim agent encoding (matching PyTorch's sinusoidal encoding).

    Components:
      - four-band reduction of reassigned diff matrix, local window of k rows
      - 4-dim sinusoidal agent encoding (matching PyTorch exactly)
    """
    n = module_positions.shape[0]

    # Compute reassigned diff matrix (matches PyTorch's curr_pairwise_norms)
    curr_norms = compute_pairwise_norms(module_positions)
    final_norms = compute_pairwise_norms(final_positions)
    diff_matrix = compute_reassigned_diff(curr_norms, final_norms, assignment)  # (n, n)

    # Apply four-band + local neighborhood reduction (matches PyTorch pipeline)
    reduced = calc_four_band_reduction(diff_matrix)  # (n, 4)
    local = calc_local_neighborhood(reduced, agent_idx, local_k)  # (k, 4)

    obs = local.flatten()  # (k*4,)

    # Normalise by max possible grid distance (matches PyTorch ogm_env.py:496)
    grid_size = jnp.float32(n * 2 + 3)  # match calculate_grid_size
    grid_size = jnp.maximum(grid_size, 5.0)
    max_dist = jnp.sqrt(3.0) * (grid_size - 1.0)
    max_dist = jnp.maximum(max_dist, 1.0)
    obs = obs / max_dist

    # Agent encoding (4 dims, matching PyTorch ogm_gym_env.py:92-106)
    # PyTorch: pos = agent_idx / max(n-1, 1)
    # [pos, sin(pos*pi), cos(pos*pi), sin(pos*2*pi)]
    pos = jnp.float32(agent_idx) / jnp.maximum(jnp.float32(n - 1), 1.0)
    agent_enc = jnp.array(
        [
            pos,
            jnp.sin(pos * jnp.pi),
            jnp.cos(pos * jnp.pi),
            jnp.sin(pos * 2.0 * jnp.pi),
        ]
    )

    return jnp.concatenate([obs, agent_enc])  # (k*4 + 4,)


# ============================================
# Environment step
# ============================================


@partial(jax.jit, static_argnums=(2, 3, 4))
def step_with_action(state: OGMState, action: int, n: int, grid_size: int, config: OGMConfig = None):
    """Execute action for the current agent and advance turn.

    Args:
        state:     current OGMState
        action:    integer in [0, 48].  48 = no-op.
        n:         number of modules (static)
        grid_size: half-width of validation grid (static)
        config:    OGMConfig with reward settings (static)

    Returns:
        (new_state, reward, terminated, truncated)
    """
    positions = state.module_positions
    agent = state.agent_idx

    # --- apply action ---
    deltas = get_action_deltas()  # (48, 3)
    # If action < 48 use the delta; otherwise (no-op) delta is 0
    delta = jnp.where(
        action < 48, deltas[jnp.clip(action, 0, 47)], jnp.zeros(3, dtype=jnp.int32)
    )
    new_positions = positions.at[agent].add(delta)

    # --- reward (with all configurable reward modes) ---
    # Use default config if none provided (backward compat)
    _config = config if config is not None else OGMConfig(
        n=n, max_steps=1000, grid_size=grid_size,
        use_unlabeled=True, local_k=7,
    )
    reward, new_m50, new_m75, new_m90, new_assignment, new_phi_max = compute_reward(
        positions,
        new_positions,
        state.final_positions,
        state.initial_norm_diff,
        state.milestone_50,
        state.milestone_75,
        state.milestone_90,
        state.curr_assignment,
        state.final_sorted_sigs,
        state.phi_max,
        state.final_sqdist,
        state.step_count,
        _config,
    )

    # --- termination ---
    terminated = check_success(new_positions, state.final_positions)
    truncated = (state.step_count + 1) >= state.max_steps

    # --- advance turn ---
    next_agent = (agent + 1) % n

    new_state = OGMState(
        module_positions=new_positions,
        final_positions=state.final_positions,
        step_count=state.step_count + 1,
        max_steps=state.max_steps,
        agent_idx=next_agent,
        initial_norm_diff=state.initial_norm_diff,
        milestone_50=new_m50,
        milestone_75=new_m75,
        milestone_90=new_m90,
        final_sorted_sigs=state.final_sorted_sigs,
        curr_assignment=new_assignment,
        phi_max=new_phi_max,
        final_sqdist=state.final_sqdist,
    )

    return new_state, reward, terminated, truncated


# ============================================
# Vectorized environment wrapper
# ============================================


class VectorizedOGMEnv:
    """Wraps config into an object with reset / step / get_action_mask.

    All methods are JIT-compiled and can be vmap-ed over a batch of keys /
    states for TPU-parallel rollout collection.
    """

    def __init__(self, config: OGMConfig):
        self.config = config
        self.n = config.n
        self.grid_size = config.grid_size
        self.local_k = config.local_k
        self.obs_dim = config.local_k * 4 + 4
        self.obs_shape = (self.obs_dim,)
        self.action_dim = NUM_ACTIONS

    # ---------- reset ----------
    @partial(jax.jit, static_argnums=(0,))
    def reset(self, key: chex.PRNGKey) -> Tuple[chex.Array, OGMState]:
        state = reset(key, self.config)
        obs = get_observation(
            state.module_positions,
            state.final_positions,
            state.agent_idx,
            self.local_k,
            state.curr_assignment,
        )
        return obs, state

    # ---------- step ----------
    @partial(jax.jit, static_argnums=(0,))
    def step(
        self, state: OGMState, action: int
    ) -> Tuple[chex.Array, OGMState, float, bool]:
        """Take one step.  Returns (obs, new_state, reward, done)."""
        new_state, reward, terminated, truncated = step_with_action(
            state, action, self.n, self.grid_size, self.config
        )
        done = terminated | truncated

        obs = get_observation(
            new_state.module_positions,
            new_state.final_positions,
            new_state.agent_idx,
            self.local_k,
            new_state.curr_assignment,
        )
        return obs, new_state, reward, done

    # ---------- action mask ----------
    @partial(jax.jit, static_argnums=(0,))
    def get_action_mask(self, state: OGMState) -> chex.Array:
        """(49,) bool mask for the current agent."""
        # Rotate positions so the acting agent is index 0
        agent = state.agent_idx
        n = self.n
        # Roll the position array so that agent becomes index 0
        rolled = jnp.roll(state.module_positions, -agent, axis=0)
        return get_action_mask(rolled, n, self.grid_size)
