"""
JAX-based Occupancy Grid Map for TPU-accelerated training.

Faithful port of the NumPy OccupancyGridMap for use with PureJaxRL-style
vectorized training on TPU.

Key design decisions:
- All state is immutable (functional updates via NamedTuple._replace).
- n (number of modules) is always a compile-time static constant; every
  function that depends on n takes it via static_argnums or receives it
  through a statically-shaped array.
- The occupancy grid is stored ONLY as an (n,3) position array.  A dense
  3D grid is reconstructed on-the-fly when pivot validation needs it.
  This avoids storing/updating a large sparse grid in traced code.
- Pivot validation uses pre-computed (48, 3, 3, 3) pattern tables that
  are exact ports of potential_pivots / ranges from the NumPy version.
- pivot_zone_grid_map is NOT ported (it is a minor optimisation in the
  original that slightly restricts legal moves after a pivot; omitting it
  makes the action space a superset of the NumPy version -- all moves the
  NumPy code allows are still allowed, plus a few extra that the zone
  mechanic would block).  This is acceptable for RL training.
- Articulation-point detection uses BFS-based connectivity checking
  (remove node, check reachability) which is JIT-compatible via lax.scan.
- Hungarian assignment for unlabeled matching uses a JAX-compatible
  implementation based on sorted-row signatures, which is exact for the
  pairwise-norm distance matrices arising in this problem.
"""

import jax
import jax.numpy as jnp
from jax import lax
from functools import partial
from typing import NamedTuple, Tuple
import chex
import numpy as np


# ============================================
# Static lookup tables (numpy, converted to
# JAX arrays at first use via _get_* helpers)
# ============================================

# --- Action deltas (48 pivots, 0-indexed) ---
# Extracted directly from take_action() in occupancy_grid_map.py.
# Row i  =>  action (i+1) in the NumPy code.
# Action 48 (index 48) is the no-op; handled separately.
_ACTION_DELTAS_NP = np.array(
    [
        # Actions  1- 4  (xy-plane, +x side)
        [1, 0, 0],
        [1, -1, 0],
        [1, 0, 0],
        [1, 1, 0],
        # Actions  5- 8  (xy-plane, +y / -y)
        [0, 1, 0],
        [1, 1, 0],
        [0, -1, 0],
        [1, -1, 0],
        # Actions  9-12  (xy-plane, -x side)
        [-1, 0, 0],
        [-1, -1, 0],
        [-1, 0, 0],
        [-1, 1, 0],
        # Actions 13-16  (xy-plane, +y / -y other)
        [0, 1, 0],
        [-1, 1, 0],
        [0, -1, 0],
        [-1, -1, 0],
        # Actions 17-20  (xz-plane, +x side)
        [1, 0, 0],
        [1, 0, -1],
        [1, 0, 0],
        [1, 0, 1],
        # Actions 21-24  (xz-plane, +z / -z)
        [0, 0, 1],
        [1, 0, 1],
        [0, 0, -1],
        [1, 0, -1],
        # Actions 25-28  (xz-plane, -x side)
        [-1, 0, 0],
        [-1, 0, -1],
        [-1, 0, 0],
        [-1, 0, 1],
        # Actions 29-32  (xz-plane, +z / -z other)
        [0, 0, 1],
        [-1, 0, 1],
        [0, 0, -1],
        [-1, 0, -1],
        # Actions 33-36  (yz-plane, +y side)
        [0, 1, 0],
        [0, 1, -1],
        [0, 1, 0],
        [0, 1, 1],
        # Actions 37-40  (yz-plane, +z / -z)
        [0, 0, 1],
        [0, 1, 1],
        [0, 0, -1],
        [0, 1, -1],
        # Actions 41-44  (yz-plane, -y side)
        [0, -1, 0],
        [0, -1, -1],
        [0, -1, 0],
        [0, -1, 1],
        # Actions 45-48  (yz-plane, +z / -z other)
        [0, 0, 1],
        [0, -1, 1],
        [0, 0, -1],
        [0, -1, -1],
    ],
    dtype=np.int32,
)  # shape (48, 3)

NUM_ACTIONS = 49  # 48 pivots + 1 no-op (index 48)

# --- Pivot validation tables ---
# Each of the 48 pivot actions requires a specific occupancy pattern in a
# 3D neighbourhood around the acting module.  The neighbourhood is defined
# by PIVOT_OFFSETS (the corner closest to the module) and extends at most
# 3 cells in each axis.  We pad everything to (48, 3, 3, 3) so shapes are
# static.
#
# PIVOT_PATTERN[a, x, y, z] == 1  means that grid cell
#     (module_pos + PIVOT_OFFSETS[a] + (x, y, z))
#   must be OCCUPIED for action a to be valid.
#
# PIVOT_CHECK[a, x, y, z] == 1   means that cell is part of the validation
#   region (cells outside are ignored).
#
# The validation rule is:
#   for every (x,y,z) where PIVOT_CHECK[a]==1:
#     occupied[cell] == bool(PIVOT_PATTERN[a, x, y, z])
#   i.e. the actual occupancy in the check region must EXACTLY equal the
#   pattern (both occupied AND empty cells must match).
#
# Generated by expanding potential_pivots[] / ranges[] from the NumPy code.

_PIVOT_PATTERN_NP = np.array(
    [
        [
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [1, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 1, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [1, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 1, 1], [0, 0, 1], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [1, 0, 0], [1, 1, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 1, 0], [1, 1, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 1], [0, 0, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 1, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [1, 1, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 1], [0, 1, 1], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 0], [0, 0, 0], [0, 1, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [1, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 1, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[0, 0, 1], [0, 0, 1], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
    ],
    dtype=np.uint8,
)  # (48, 3, 3, 3)

_PIVOT_CHECK_NP = np.array(
    [
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
            [[1, 0, 0], [1, 0, 0], [1, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
            [[1, 1, 1], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [1, 1, 0], [1, 1, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [1, 1, 0], [1, 1, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [1, 1, 0], [1, 1, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 0], [1, 1, 0], [1, 1, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
        [
            [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
            [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        ],
    ],
    dtype=np.uint8,
)  # (48, 3, 3, 3)

# Corner offset (relative to module position) for each action's 3x3x3 check window.
_PIVOT_OFFSETS_NP = np.array(
    [
        [0, -1, 0],
        [0, -1, 0],
        [0, -1, 0],
        [0, -1, 0],
        [-1, 0, 0],
        [-1, 0, 0],
        [-1, -1, 0],
        [-1, -2, 0],
        [-1, -1, 0],
        [-2, -1, 0],
        [-1, -1, 0],
        [-2, -1, 0],
        [-1, 0, 0],
        [-1, 0, 0],
        [-1, -1, 0],
        [-1, -2, 0],
        [0, 0, -1],
        [0, 0, -1],
        [0, 0, -1],
        [0, 0, -1],
        [-1, 0, 0],
        [-1, 0, 0],
        [-1, 0, -1],
        [-1, 0, -2],
        [-1, 0, -1],
        [-2, 0, -1],
        [-1, 0, -1],
        [-2, 0, -1],
        [-1, 0, 0],
        [-1, 0, 0],
        [-1, 0, -1],
        [-1, 0, -2],
        [0, 0, -1],
        [0, 0, -1],
        [0, 0, -1],
        [0, 0, -1],
        [0, -1, 0],
        [0, -1, 0],
        [0, -1, -1],
        [0, -1, -2],
        [0, -1, -1],
        [0, -2, -1],
        [0, -1, -1],
        [0, -2, -1],
        [0, -1, 0],
        [0, -1, 0],
        [0, -1, -1],
        [0, -1, -2],
    ],
    dtype=np.int32,
)  # (48, 3)


# ---- Eager JAX constant arrays (converted at import time, never inside JIT) ----
# These are static lookup tables; converting them once at module load avoids
# tracer-leak errors that occur if conversion happens inside a jit-traced call.
ACTION_DELTAS = jnp.array(_ACTION_DELTAS_NP)  # (48, 3)  int32
PIVOT_PATTERN = jnp.array(_PIVOT_PATTERN_NP)  # (48, 3, 3, 3) uint8
PIVOT_CHECK = jnp.array(_PIVOT_CHECK_NP)  # (48, 3, 3, 3) uint8
PIVOT_OFFSETS = jnp.array(_PIVOT_OFFSETS_NP)  # (48, 3)  int32


def get_action_deltas():
    return ACTION_DELTAS


def get_pivot_pattern():
    return PIVOT_PATTERN


def get_pivot_check():
    return PIVOT_CHECK


def get_pivot_offsets():
    return PIVOT_OFFSETS


# ============================================
# Data Structures
# ============================================


class OGMState(NamedTuple):
    """Immutable state for one environment instance."""

    module_positions: chex.Array  # (n, 3) int32 - current positions
    final_positions: chex.Array  # (n, 3) int32 - target positions
    step_count: int  # current step (scalar int32)
    max_steps: int  # episode length limit (scalar int32)
    # agent_idx tracks whose turn it is (round-robin)
    agent_idx: int  # scalar int32


class OGMConfig(NamedTuple):
    """Static (non-traced) configuration."""

    n: int
    max_steps: int
    grid_size: int  # half-width for the dense grid used in validation
    use_unlabeled: bool
    local_k: int


# ============================================
# Utility: build a dense occupancy grid from
# (n,3) positions.  grid_size must be large
# enough that all positions fit inside
# [0, 2*grid_size).
# ============================================


@partial(jax.jit, static_argnums=(1,))
def _build_grid(positions: chex.Array, grid_size: int) -> chex.Array:
    """Return a (2*gs, 2*gs, 2*gs) bool grid marking occupied cells."""
    side = 2 * grid_size
    grid = jnp.zeros((side, side, side), dtype=jnp.bool_)

    # scatter True at each position
    def _set(g, pos):
        return g.at[pos[0], pos[1], pos[2]].set(True), None

    grid, _ = lax.scan(_set, grid, positions)
    return grid


# ============================================
# Core: pairwise norms
# ============================================


@jax.jit
def compute_pairwise_norms(positions: chex.Array) -> chex.Array:
    """(n,3) -> (n,n) L2 distances."""
    diff = positions[:, None, :] - positions[None, :, :]  # (n, n, 3)
    return jnp.sqrt(jnp.sum(diff * diff, axis=-1))


# ============================================
# Observation reductions (four-band + local-k)
# ============================================


@jax.jit
def calc_four_band_reduction(pairwise_norms: chex.Array) -> chex.Array:
    """(n,n) -> (n,4).  Offsets [-2,-1,+1,+2] with circular wrapping."""
    n = pairwise_norms.shape[0]
    idx = jnp.arange(n)
    bands = []
    for offset in [-2, -1, 1, 2]:
        j = (idx + offset) % n
        bands.append(pairwise_norms[idx, j])  # (n,)
    return jnp.stack(bands, axis=1)  # (n, 4)


@partial(jax.jit, static_argnums=(2,))
def calc_local_neighborhood(reduced: chex.Array, agent_idx: int, k: int) -> chex.Array:
    """(n, 4) -> (k, 4) window centred on agent_idx."""
    n = reduced.shape[0]
    half_k = k // 2
    offsets = jnp.arange(k) - half_k  # (-half_k .. k-half_k-1)
    indices = (agent_idx + offsets) % n
    return reduced[indices]  # (k, 4)


# ============================================
# Connectivity & articulation-point detection
# ============================================


@partial(jax.jit, static_argnums=(1,))
def _build_adjacency(positions: chex.Array, n: int) -> chex.Array:
    """Return (n,n) bool adjacency matrix (Manhattan dist == 1)."""
    diff = positions[:, None, :] - positions[None, :, :]  # (n,n,3)
    manhattan = jnp.sum(jnp.abs(diff), axis=-1)  # (n,n)
    return manhattan == 1  # (n,n) bool


@partial(jax.jit, static_argnums=(2,))
def _bfs_reachable(adj: chex.Array, start: int, n: int) -> chex.Array:
    """BFS from `start` using matrix-power expansion.  Returns (n,) bool visited."""
    visited = jnp.zeros(n, dtype=jnp.bool_).at[start].set(True)

    def _step(visited, _):
        # any neighbour of a visited node becomes visited
        new_visited = jnp.any(adj & visited[None, :], axis=1) | visited
        return new_visited, None

    visited, _ = lax.scan(_step, visited, None, length=n)
    return visited


@partial(jax.jit, static_argnums=(1,))
def is_articulation_point(positions: chex.Array, n: int) -> chex.Array:
    """Return (n,) bool array: True where module is an articulation point.

    A module is an AP if removing it disconnects the remaining graph.
    We check this by: for each candidate i, mask row/col i out of the
    adjacency matrix, pick the first remaining node as BFS root, and
    check if all other remaining nodes are reached.
    """
    adj = _build_adjacency(positions, n)  # (n,n)

    def _check_one(i):
        # mask out node i
        mask = jnp.arange(n) != i  # (n,) bool
        adj_masked = adj & mask[:, None] & mask[None, :]  # zero row & col i

        # BFS root: first node that is not i
        # Use (i+1) % n so it wraps around
        root = (i + 1) % n

        visited = _bfs_reachable(adj_masked, root, n)  # (n,)

        # All nodes except i must be visited
        expected = mask  # (n,) True everywhere except i
        return ~jnp.all(visited == expected)  # True => disconnected => AP

    return jax.vmap(_check_one)(jnp.arange(n))  # (n,)


# ============================================
# Pivot validation (action mask)
# ============================================


@partial(jax.jit, static_argnums=(1, 2))
def get_action_mask(positions: chex.Array, n: int, grid_size: int) -> chex.Array:
    """Return (49,) bool mask of valid actions for agent at positions[agent_idx].

    Checks:
      1. Module must NOT be an articulation point.
      2. For each of the 48 pivot actions, the 3x3x3 neighbourhood occupancy
         must exactly match the pre-computed PIVOT_PATTERN (ports the
         potential_pivots check from the NumPy version).
      3. Action 48 (no-op) is always valid.

    agent_idx is encoded implicitly: this function returns the mask for
    agent 0.  The caller rotates the position array so that the acting
    agent is always index 0 -- see _rotate_for_agent().
    """
    # --- build dense grid ---
    # Shift positions so minimum is at least 2 (buffer for negative offsets
    # in PIVOT_OFFSETS which go down to -2).
    # We use a fixed shift of grid_size so that positions land in the middle.
    shifted = positions + grid_size  # (n, 3) int32
    side = 2 * grid_size
    grid = _build_grid(shifted, grid_size)  # (side,side,side) bool

    # --- articulation point for agent 0 ---
    ap_mask = is_articulation_point(positions, n)  # (n,)
    agent_is_ap = ap_mask[0]  # scalar bool

    # --- pattern check for all 48 actions ---
    agent_pos = shifted[0]  # (3,) shifted position of agent 0

    pattern = get_pivot_pattern()  # (48, 3, 3, 3) uint8
    check = get_pivot_check()  # (48, 3, 3, 3) uint8
    offsets = get_pivot_offsets()  # (48, 3) int32

    def _check_action(a):
        """Check one pivot action a in [0..47]."""
        # Corner of the 3x3x3 window in the shifted grid
        corner = agent_pos + offsets[a]  # (3,)

        # Extract the 3x3x3 sub-grid.  Use dynamic_slice (JIT-safe).
        sub = lax.dynamic_slice(grid, corner, (3, 3, 3))  # (3,3,3) bool

        # Compare: where check==1, sub must equal pattern
        pat = pattern[a].astype(jnp.bool_)  # (3,3,3)
        chk = check[a].astype(jnp.bool_)  # (3,3,3)

        # Mismatch at any checked cell => invalid
        mismatch = chk & (sub != pat)
        return ~jnp.any(mismatch)  # True => valid

    pivot_valid = jax.vmap(_check_action)(jnp.arange(48))  # (48,) bool

    # If agent is AP, no pivot is valid
    pivot_valid = jnp.where(agent_is_ap, jnp.zeros(48, dtype=jnp.bool_), pivot_valid)

    # Append no-op (always valid)
    return jnp.concatenate([pivot_valid, jnp.array([True])])  # (49,)


# ============================================
# Success check (unlabeled: sorted-row
# signature matching, equivalent to the
# Hungarian-based check for distance matrices)
# ============================================


@jax.jit
def check_success(
    module_positions: chex.Array, final_positions: chex.Array, tol: float = 1e-6
) -> bool:
    """True if the current shape matches the target (up to rigid motion)."""
    curr = compute_pairwise_norms(module_positions)
    final = compute_pairwise_norms(final_positions)
    # Sort each row -> canonical shape signature
    curr_sorted = jnp.sort(curr, axis=1)
    final_sorted = jnp.sort(final, axis=1)
    # Sort the rows themselves so the signature is permutation-invariant
    curr_sig = jnp.sort(curr_sorted, axis=0)
    final_sig = jnp.sort(final_sorted, axis=0)
    return jnp.allclose(curr_sig, final_sig, atol=tol)


# ============================================
# Reward / potential
# ============================================


@jax.jit
def compute_potential(
    module_positions: chex.Array, final_positions: chex.Array
) -> float:
    """Potential Phi(s) = - sum |curr_sorted - final_sorted| (row-wise).

    Lower (closer to 0) is better; Phi == 0 at success.
    """
    curr = compute_pairwise_norms(module_positions)
    final = compute_pairwise_norms(final_positions)
    curr_sorted = jnp.sort(curr, axis=1)
    final_sorted = jnp.sort(final, axis=1)
    # Sort rows for permutation invariance (matches check_success logic)
    curr_sig = jnp.sort(curr_sorted, axis=0)
    final_sig = jnp.sort(final_sorted, axis=0)
    return jnp.sum(jnp.abs(curr_sig - final_sig))


@partial(jax.jit, static_argnums=())
def compute_reward(
    prev_positions: chex.Array,
    curr_positions: chex.Array,
    final_positions: chex.Array,
    step_cost: float = -0.005,
    potential_scale: float = 1.0,
    success_bonus: float = 100.0,
) -> float:
    """Shaped reward: step_cost + potential shaping + success bonus."""
    prev_phi = compute_potential(prev_positions, final_positions)
    curr_phi = compute_potential(curr_positions, final_positions)

    shaping = potential_scale * (prev_phi - curr_phi)  # positive when improving
    done = check_success(curr_positions, final_positions)
    bonus = jnp.where(done, success_bonus, 0.0)

    return step_cost + shaping + bonus


# ============================================
# Random connected configuration generator
# ============================================


@partial(jax.jit, static_argnums=(1,))
def make_connected_configuration(key: chex.PRNGKey, n: int) -> chex.Array:
    """Grow a random connected structure of n cubes via BFS-style growth.

    Returns (n, 3) int32 positions centred near the origin.
    """
    # 6 face-adjacent directions
    DIRS = jnp.array(
        [[1, 0, 0], [-1, 0, 0], [0, 1, 0], [0, -1, 0], [0, 0, 1], [0, 0, -1]],
        dtype=jnp.int32,
    )

    # Start at origin
    positions = jnp.zeros((n, 3), dtype=jnp.int32)  # pre-allocated
    filled = jnp.zeros(n, dtype=jnp.bool_).at[0].set(True)

    def _add_one(carry, key_i):
        positions, filled, count = carry

        # For every filled position, compute 6 candidate neighbours
        # Shape: (n, 6, 3)
        candidates = positions[:, None, :] + DIRS[None, :, :]
        candidates_flat = candidates.reshape(-1, 3)  # (n*6, 3)

        # Mask: candidate comes from a filled slot
        from_filled = jnp.repeat(filled, 6)  # (n*6,)

        # Mask: candidate is not already occupied
        def _is_free(pos):
            matches = jnp.all(positions == pos[None, :], axis=1) & filled
            return ~jnp.any(matches)

        free_mask = jax.vmap(_is_free)(candidates_flat)  # (n*6,)

        valid = from_filled & free_mask  # (n*6,)

        # Sample uniformly among valid candidates
        logits = jnp.where(valid, 0.0, -1e9)
        idx = jax.random.categorical(key_i, logits)

        new_pos = candidates_flat[idx]  # (3,)
        positions = positions.at[count].set(new_pos)
        filled = filled.at[count].set(True)

        return (positions, filled, count + 1), None

    keys = jax.random.split(key, n - 1)
    (positions, _, _), _ = lax.scan(_add_one, (positions, filled, 1), keys)

    return positions


# ============================================
# Environment reset
# ============================================


@partial(jax.jit, static_argnums=(1,))
def reset(key: chex.PRNGKey, config: OGMConfig) -> OGMState:
    """Create a fresh episode with random initial & target configurations."""
    key1, key2 = jax.random.split(key)
    init_pos = make_connected_configuration(key1, config.n)
    final_pos = make_connected_configuration(key2, config.n)

    return OGMState(
        module_positions=init_pos,
        final_positions=final_pos,
        step_count=jnp.int32(0),
        max_steps=jnp.int32(config.max_steps),
        agent_idx=jnp.int32(0),
    )


# ============================================
# Observation
# ============================================


@partial(jax.jit, static_argnums=(3,))
def get_observation(
    module_positions: chex.Array,
    final_positions: chex.Array,
    agent_idx: int,
    local_k: int,
) -> chex.Array:
    """Flat observation vector of size (local_k * 4 + 4).

    Components:
      - four-band reduction of |curr_norms - final_norms|, local window of k rows
      - 4-dim sinusoidal agent encoding
    """
    n = module_positions.shape[0]

    curr_norms = compute_pairwise_norms(module_positions)
    final_norms = compute_pairwise_norms(final_positions)
    rel_norms = jnp.abs(curr_norms - final_norms)  # (n, n)

    reduced = calc_four_band_reduction(rel_norms)  # (n, 4)
    local = calc_local_neighborhood(reduced, agent_idx, local_k)  # (k, 4)

    obs = local.flatten()  # (k*4,)

    # Normalise by max possible grid distance
    max_dist = jnp.sqrt(3.0) * 50.0
    obs = obs / max_dist

    # Agent encoding (4 dims, fixed size)
    n_f = jnp.float32(n)
    idx_f = jnp.float32(agent_idx)
    agent_enc = jnp.array(
        [
            jnp.sin(2.0 * jnp.pi * idx_f / n_f),
            jnp.cos(2.0 * jnp.pi * idx_f / n_f),
            idx_f / n_f,
            (n_f - idx_f) / n_f,
        ]
    )

    return jnp.concatenate([obs, agent_enc])  # (k*4 + 4,)


# ============================================
# Environment step
# ============================================


@partial(jax.jit, static_argnums=(2, 3))
def step_with_action(state: OGMState, action: int, n: int, grid_size: int):
    """Execute action for the current agent and advance turn.

    Args:
        state:     current OGMState
        action:    integer in [0, 48].  48 = no-op.
        n:         number of modules (static)
        grid_size: half-width of validation grid (static)

    Returns:
        (new_state, reward, terminated, truncated)
    """
    positions = state.module_positions
    agent = state.agent_idx

    # --- apply action ---
    deltas = get_action_deltas()  # (48, 3)
    # If action < 48 use the delta; otherwise (no-op) delta is 0
    delta = jnp.where(
        action < 48, deltas[jnp.clip(action, 0, 47)], jnp.zeros(3, dtype=jnp.int32)
    )
    new_positions = positions.at[agent].add(delta)

    # --- reward ---
    reward = compute_reward(positions, new_positions, state.final_positions)

    # --- termination ---
    terminated = check_success(new_positions, state.final_positions)
    truncated = (state.step_count + 1) >= state.max_steps

    # --- advance turn ---
    next_agent = (agent + 1) % n

    new_state = OGMState(
        module_positions=new_positions,
        final_positions=state.final_positions,
        step_count=state.step_count + 1,
        max_steps=state.max_steps,
        agent_idx=next_agent,
    )

    return new_state, reward, terminated, truncated


# ============================================
# Vectorized environment wrapper
# ============================================


class VectorizedOGMEnv:
    """Wraps config into an object with reset / step / get_action_mask.

    All methods are JIT-compiled and can be vmap-ed over a batch of keys /
    states for TPU-parallel rollout collection.
    """

    def __init__(self, config: OGMConfig):
        self.config = config
        self.n = config.n
        self.grid_size = config.grid_size
        self.local_k = config.local_k
        self.obs_dim = config.local_k * 4 + 4
        self.obs_shape = (self.obs_dim,)
        self.action_dim = NUM_ACTIONS

    # ---------- reset ----------
    @partial(jax.jit, static_argnums=(0,))
    def reset(self, key: chex.PRNGKey) -> Tuple[chex.Array, OGMState]:
        state = reset(key, self.config)
        obs = get_observation(
            state.module_positions, state.final_positions, state.agent_idx, self.local_k
        )
        return obs, state

    # ---------- step ----------
    @partial(jax.jit, static_argnums=(0,))
    def step(
        self, state: OGMState, action: int
    ) -> Tuple[chex.Array, OGMState, float, bool]:
        """Take one step.  Returns (obs, new_state, reward, done)."""
        new_state, reward, terminated, truncated = step_with_action(
            state, action, self.n, self.grid_size
        )
        done = terminated | truncated

        obs = get_observation(
            new_state.module_positions,
            new_state.final_positions,
            new_state.agent_idx,
            self.local_k,
        )
        return obs, new_state, reward, done

    # ---------- action mask ----------
    @partial(jax.jit, static_argnums=(0,))
    def get_action_mask(self, state: OGMState) -> chex.Array:
        """(49,) bool mask for the current agent."""
        # Rotate positions so the acting agent is index 0
        agent = state.agent_idx
        n = self.n
        # Roll the position array so that agent becomes index 0
        rolled = jnp.roll(state.module_positions, -agent, axis=0)
        return get_action_mask(rolled, n, self.grid_size)
